name: Deploy to VPS

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: '{{defaultContext}}'
          push: true
          tags: leogues/portfolio-frontend:latest, leogues/portfolio-frontend:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: SSH Deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          password: ${{ secrets.SSH_PASSWORD}}
          script: |
            cd ../srv/portfolio
            chmod +x deploy-script
            ./deploy-script
